name: "Hello world"
description: "Greet someone and record the time"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
  output-dir:
    desription: "Output directory"
    required: true
    default: ${{ github.workspace }}/default-out
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.output-dir }}
    - ${{ inputs.who-to-greet }}

